// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5DKcVqEa2GKAwPd6LhsfbEV72JoVNnhc',
    appId: '1:347946496466:web:9cd4be2bca49a705be980b',
    messagingSenderId: '347946496466',
    projectId: 'telemedicine-app-3fcd8',
    authDomain: 'telemedicine-app-3fcd8.firebaseapp.com',
    storageBucket: 'telemedicine-app-3fcd8.appspot.com',
    measurementId: 'G-7571BQJEVL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMpzqUr5ydnHncbM70qe4MHH-MhblviYI',
    appId: '1:347946496466:android:e8a8c00dbc34c4f9be980b',
    messagingSenderId: '347946496466',
    projectId: 'telemedicine-app-3fcd8',
    storageBucket: 'telemedicine-app-3fcd8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJ_dJll_-kO4N-yebv4IVxL5cjKAQlIj8',
    appId: '1:347946496466:ios:d176f54679caa0cdbe980b',
    messagingSenderId: '347946496466',
    projectId: 'telemedicine-app-3fcd8',
    storageBucket: 'telemedicine-app-3fcd8.appspot.com',
    androidClientId: '347946496466-7jt9jkt800bnj894g3jqapr6kvoahsfh.apps.googleusercontent.com',
    iosClientId: '347946496466-6rig5l4u4g433aeunmpc2anqb7b7q1de.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJ_dJll_-kO4N-yebv4IVxL5cjKAQlIj8',
    appId: '1:347946496466:ios:d176f54679caa0cdbe980b',
    messagingSenderId: '347946496466',
    projectId: 'telemedicine-app-3fcd8',
    storageBucket: 'telemedicine-app-3fcd8.appspot.com',
    androidClientId: '347946496466-7jt9jkt800bnj894g3jqapr6kvoahsfh.apps.googleusercontent.com',
    iosClientId: '347946496466-6rig5l4u4g433aeunmpc2anqb7b7q1de.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAuth',
  );
}
